# Find more details about this configuration file at http://github.com/fnando/i18n-js
translations:
  - file: "public/javascripts/translations/en.js"
    only: "en.*"
  - file: "public/javascripts/translations/es.js"
    only: "es.*"